include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - public_member_api_docs

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
